name:                wordle
version:             0.1.0.0
github:              "crypt0s1s/wordle"
license:             BSD3
author:              "Joshua Sumskas"
maintainer:          "crypt0sis@protonmail.com"
copyright:           "2022 Joshua Sumskas"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/crypt0s1s/wordle#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - split
  - multiset
  - containers
  - mtl
  - random

executables:
  wordle-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wordle

tests:
  wordle-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wordle
